---
title: "R Notebook"
output: html_notebook
---

Doxy-PEP Model
E Reichert, 10.2023

Explore impact of doxy-PEP if entire US MSM-like population we model is eligible
(No restriction by sexual activity group)

```{r}
#load necessary packages
library(tidyverse)
library(deSolve)
library(RColorBrewer)
library(showtext)
library(reshape2)
library(stringr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)

# Enter file path for folder where doxy-PEP code is stored
filepath <- "~/Documents/2021 Grad lab research/DOXYPEP/"

source(paste0(filepath, "DoxyPEPcode/DOXYfunctions.R"))
```

I. Set parameters and initial conditions.
```{r}
# Set parameters that will stay constant throughout model
pop = 10^6                    #pop size
pop.p = c(0.3, 0.6, 0.1)      #relative size of each risk group; low, M, high
c_min = 1.4076374
activities = c(1*c_min/365, 
               5*c_min/365, 
               20*c_min/365)  #sexual contacts per day
epsilon = 0.2544778           #mixing parameter

#PARAM VALUES
# including those determined through SEIScalibration.R MLE procedure
b = 0.5517084        #transmission Pr per partnership
sigma = 0.4531209    #Pr of symptomatic infection
g = 1/76.3540493     #natural recovery rate from infection
Ts = 1/15.3720017    #time to treatment for symptomatic infection
Tm = 0.3569368/365   #screening rate (time to treatment for asymptomatic infection)
rho = 1/(20*365)     #model entry/exit rate
omega_a = 10^-8      #Pr of emergence of resistance on treatment with A (ceftriaxone)
omega_b = 0          #Pr of emergence of resistance on treatment with B (doxy)
prA = 1              #Pr of treatment with A
prB = 0              #Pr of DOXYPEP (vary this coverage %)
fA = 0.98            #relative fitness, resistant to A
fB = 0.98            #relative fitness, resistant to B (is this reasonable??)
fAB = fA*fB          #relative fitness, dual resistance
pi_s = 0.90          #Pr of retreatment if initial treatment failure, symptomatic
Tsr = Ts/3           #time to retreatment for symptomatic infection, if failure
resA = 0.0001        #initial prev of resistance to A
resB = 0.109         #initial prev of resistance to doxy
gamma = 1/(1)        #rate of recovery from exposure
kappa = 0.38         #proportion of doxyPEP treatments that fail (not due to resistance)
```

```{r}
years = 20
tstep = 1 #in days
  
#set N for each sexual risk group (1 = lo risk, 2 = med risk, 3 = hi risk)
N <- pop
N1 <- N*pop.p[1]
N2 <- N*pop.p[2]
N3 <- N*pop.p[3]

#estimated prevalence of GC in each sexual activity group, @ equilibrium
# (mean from calibration model run; gives overall weighted GC prev of 3.0%)
gc_lo <- round(N1*0.00480,0)
gc_md <- round(N2*0.02576,0)
gc_hi <- round(N3*0.13719,0)

#estimated proportion of symp. infections at cross-sectional point in time, @ equilibrium
# (mean from calibration model run, 13%)
prev_symp <- 0.13
Y_gc_lo <- gc_lo*prev_symp
Z_gc_lo <- gc_lo*(1-prev_symp)
Y_gc_md <- gc_md*prev_symp
Z_gc_md <- gc_md*(1-prev_symp)
Y_gc_hi <- gc_hi*prev_symp
Z_gc_hi <- gc_hi*(1-prev_symp)

Y0 <- c(Y_gc_lo, Y_gc_md, Y_gc_hi) * (1-(resA + resB - resA*resB))
Z0 <- c(Z_gc_lo, Z_gc_md, Z_gc_hi) * (1-(resA + resB - resA*resB))

YA <- c(Y_gc_lo, Y_gc_md, Y_gc_hi) * resA * (1-resB)
ZA <- c(Z_gc_lo, Z_gc_md, Z_gc_hi) * resA * (1-resB)

YB <- c(Y_gc_lo, Y_gc_md, Y_gc_hi) * resB * (1-resA)
ZB <- c(Z_gc_lo, Z_gc_md, Z_gc_hi) * resB * (1-resA)

YAB <- c(Y_gc_lo, Y_gc_md, Y_gc_hi) * (resA*resB)
ZAB <- c(Z_gc_lo, Z_gc_md, Z_gc_hi) * (resA*resB)

#estimated proportion of individuals exposed at cross-sectional point in time, @ equilibrium
# (mean from calibration model run, 0.07%)
prev_exp <- 0.0007
exp_lo <- round(N1*prev_exp,0)
exp_md <- round(N2*prev_exp,0)
exp_hi <- round(N3*prev_exp,0)

E0 <- c(gc_lo, gc_md, gc_hi) * 0.016 * (1-(resA + resB - resA*resB))
Ea <- c(gc_lo, gc_md, gc_hi) * 0.016 * resA * (1-resB)
Eb <- c(gc_lo, gc_md, gc_hi) * 0.016 * resB * (1-resA)
Eab <- c(gc_lo, gc_md, gc_hi) * 0.016 * resA*resB

E0 <- c(exp_lo, exp_md, exp_hi) * (1-(resA + resB - resA*resB))
Ea <- c(exp_lo, exp_md, exp_hi) * resA * (1-resB)
Eb <- c(exp_lo, exp_md, exp_hi) * resB * (1-resA)
Eab<- c(exp_lo, exp_md, exp_hi) * resA * resB

#start with overall prevalence of 3% of gonorrhea
inits <- c(S1 = N1-gc_lo-exp_lo, S2 = N2-gc_md-exp_md, S3 = N3-gc_hi-exp_hi,
           E01 = E0[1], E02 = E0[2], E03 = E0[3], 
           Y01 = Y0[1], Y02 = Y0[2], Y03 = Y0[3],
           Z01 = Z0[1], Z02 = Z0[2], Z03 = Z0[3],
           Ea1 = Ea[1], Ea2 = Ea[2], Ea3 = Ea[3],
           Ya1 = YA[1], Ya2 = YA[2], Ya3 = YA[3],
           Za1 = ZA[1], Za2 = ZA[2], Za3 = ZA[3],
           Eb1 = Eb[1], Eb2 = Eb[2], Eb3 = Eb[3],
           Yb1 = YB[1], Yb2 = YB[2], Yb3 = YB[3], 
           Zb1 = ZB[1], Zb2 = ZB[2], Zb3 = ZB[3],
           Eab1 = Eab[1], Eab2 = Eab[2], Eab3 = Eab[3],
           Yab1 = YAB[1], Yab2 = YAB[2], Yab3 = YAB[3],
           Zab1 = ZAB[1], Zab2 = ZAB[2], Zab3 = ZAB[3])

```

```{r}
dt <- seq(0, 365*years, tstep)

#list out parameters defined above
parms <- list(g=g, 
              pop=pop, 
              pop.p=pop.p, 
              epsilon=epsilon, 
              c_min = c_min,
              b = b, 
              sigma = sigma, 
              Ts = Ts, 
              Tm = Tm, 
              rho = rho, 
              prA = prA, 
              prB = prB, 
              omega_a = omega_a, 
              omega_b = omega_b, 
              fA = fA, fB = fB, 
              fAB = fAB, 
              pi_s = pi_s, 
              Tsr = Tsr,
              gamma = gamma,
              kappa = kappa)
```

II. Run DoxyPEP Model

```{r}
#Set up the ODE system of equations
doxyPEP.SI <- function(t, x, parms){
    with(as.list(c(t, x, parms)),{
    N = c(N1, N2, N3) #total population
    S = c(S1, S2, S3) #not infected
    E0 = c(E01, E02, E03)
    Ea = c(Ea1, Ea2, Ea3)
    Eb = c(Eb1, Eb2, Eb3)
    Eab = c(Eab1, Eab2, Eab3)
    Y0 = c(Y01, Y02, Y03) #symptomatic infected, no resistance
    Ya = c(Ya1, Ya2, Ya3) #symptomatic infected, resistant to A
    Yb = c(Yb1, Yb2, Yb3)
    Yab = c(Yab1, Yab2, Yab3)
    Z0 = c(Z01, Z02, Z03) #asymptomatic infected, no resistance
    Za = c(Za1, Za2, Za3) #asymptomatic infected, resistant to A
    Zb = c(Zb1, Zb2, Zb3)
    Zab = c(Zab1, Zab2, Zab3)
        
     #makes 3x3 contact matrix
    activities <- c(1*c_min/365, 5*c_min/365, 20*c_min/365)
    beta <- (1-epsilon)*outer(activities, activities)/sum(pop*pop.p*activities) + 
      epsilon*activities/(pop*pop.p)*diag(3)
    beta <- beta * b #contacts * transmission pr per partnership
    
    #keep track of prev resistance to B
    prevA = (sum(Ya) + sum(Za) + sum(Yab) + sum(Zab))/(sum(Y0) + sum(Z0) + sum(Ya) + sum(Za) + sum(Yb)+sum(Zb)+sum(Yab)+sum(Zab))
    prevB = (sum(Yb) + sum(Zb) + sum(Yab) + sum(Zab))/(sum(Y0) + sum(Z0) + sum(Ya) + sum(Za) + sum(Yb)+sum(Zb)+sum(Yab)+sum(Zab))
    prevAB = (sum(Yab) + sum(Zab))/(sum(Y0) + sum(Z0) + sum(Ya) + sum(Za) + sum(Yb)+sum(Zb)+sum(Yab)+sum(Zab))
    prev0 = (sum(Y0) + sum(Z0))/(sum(Y0) + sum(Z0) + sum(Ya) + sum(Za) + sum(Yb)+sum(Zb)+sum(Yab)+sum(Zab))
    #keep track of inc infections each day
    Inc = sum(beta %*% ((Y0 + Z0) + fA*(Ya+Za) + fB*(Yb+Zb) + fAB*(Yab+Zab))*S)
    prevGC = (sum(Y0) + sum(Z0) + sum(Ya) + sum(Za) + sum(Yb)+sum(Zb)+sum(Yab)+sum(Zab))/10^6
    ARx = sum(Ts*Y0 + Tm*Z0 + pi_s*Tsr*Ya + Ts*Yb + Tm*Zb + pi_s*Tsr*Yab)
    BRx = sum(prB*gamma*(E0 + Ea + Eb + Eab))
    
    #susceptibles
    dS <- -beta %*% ((Y0 + Z0) + fA*(Ya+Za) + fB*(Yb+Zb) + fAB*(Yab+Zab))*S +
      (1-omega_a)*(Ts*Y0 + Tm*Z0) +
      pi_s*(Tsr*Ya + Tsr*Yab) +
      (1-omega_a)*(Ts*Yb + Tm*Zb) +
      prB*(1-kappa)*(1-omega_b)*(gamma*E0 + gamma*Ea) +
      g*(Y0 + Ya + Z0 + Za + Yb + Zb + Yab + Zab) + 
      rho*(S + Y0 + Ya + Z0 + Za + Yb + Zb + Yab + Zab) - rho*S
    #infections w/ no resistance
    dE0 <- (beta %*% (Y0+Z0)*S) - gamma*E0
    dY0 <- sigma*(1-prB)*(gamma*E0) + sigma*prB*kappa*(1-omega_b)*(gamma*E0) - 
      g*Y0 - rho*Y0 - Ts*Y0
    dZ0 <- (1-sigma)*(1-prB)*(gamma*E0) + (1-sigma)*prB*kappa*(1-omega_b)*(gamma*E0) - 
      g*Z0 - rho*Z0 - Tm*Z0
    #infections w/ resistance to A
    dEa <- fA*(beta %*% (Ya+Za)*S) - gamma*Ea
    dYa <- sigma*(1-prB)*(gamma*Ea) + 
      sigma*prB*kappa*(1-omega_b)*(gamma*Ea) +
      omega_a*Ts*Y0 -
      g*Ya - rho*Ya - 
      pi_s*Tsr*Ya
    dZa <- (1-sigma)*(1-prB)*(gamma*Ea) + 
      (1-sigma)*prB*kappa*(1-omega_b)*(gamma*Ea) + 
      omega_a*Tm*Z0 -
      g*Za - rho*Za
    #infections w/ resistance to B
    dEb <- fB*(beta %*% (Yb+Zb)*S) - gamma*Eb
    dYb <- sigma*gamma*Eb + sigma*prB*omega_b*(gamma*E0) -
      g*Yb - rho*Yb - Ts*Yb
    dZb <- (1-sigma)*gamma*Eb + (1-sigma)*prB*omega_b*(gamma*E0)-
      g*Zb - rho*Zb - Tm*Zb
    #infections w/ dual resistance
    dEab <- fAB*(beta %*% (Yab+Zab)*S) - gamma*Eab
    dYab <- sigma*gamma*Eab + sigma*prB*omega_b*(gamma*Ea) +
      omega_a*Ts*Yb - 
      pi_s*Tsr*Yab -
      g*Yab - rho*Yab
    dZab <- (1-sigma)*gamma*Eab + (1-sigma)*prB*omega_b*(gamma*Ea) +
      omega_a*Tm*Zb -
      g*Zab - rho*Zab
    der <- c(dS, dE0, dY0, dZ0, dEa, dYa, dZa, dEb, dYb, dZb, dEab, dYab, dZab)
    list(der, Inc = Inc, prevA = prevA, prevB = prevB, prevAB = prevAB, prev0 = prev0, 
         prevGC = prevGC, ARx = ARx, BRx = BRx)
  })
}
```

```{r}
#run ODE models over all combinations of these params
RunODE <- function (x) {
  #provide column names
      parms$prB <- x
      doxy_sim <- as.data.frame(ode(inits, dt, doxyPEP.SI, parms=parms))   
  return(doxy_sim)
}

temp <- lapply(X = c(0,0.1,0.25,0.5,0.75, 0.9), RunODE)
# names(temp) <- c("doxy_sim0", "doxy_sim10", "doxy_sim25", "doxy_sim50", "doxy_sim75")
# list2env(temp, envir = .GlobalEnv)
doxy_sim0 <- temp[[1]]
doxy_sim10 <- temp[[2]]
doxy_sim25 <- temp[[3]]
doxy_sim50 <- temp[[4]]
doxy_sim75 <- temp[[5]]
doxy_sim90 <- temp[[6]]
```

III. Analyze Model Output

```{r}
 #ensure the total pop size does not change
doxy_sim0 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum) %>% summarise(min(RowSum), max(RowSum))
doxy_sim10 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum)%>% summarise(min(RowSum), max(RowSum))
doxy_sim25 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum)%>% summarise(min(RowSum), max(RowSum))
doxy_sim50 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum)%>% summarise(min(RowSum), max(RowSum))
doxy_sim75 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum)%>% summarise(min(RowSum), max(RowSum))
doxy_sim90 %>% mutate(RowSum=rowSums(.[setdiff(names(.),c("time", "Inc", "prevB", "prevA", "prevAB", "prev0", "prevGC", "ARx", "BRx"))])) %>% 
  select(RowSum)%>% summarise(min(RowSum), max(RowSum))

```

```{r}
df_list <- list(doxy_sim0 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0, -prevGC, -ARx, -BRx), 
                doxy_sim10 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0,-prevGC, -ARx, -BRx), 
                doxy_sim25 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0, -prevGC, -ARx, -BRx), 
                doxy_sim50 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0, -prevGC, -ARx, -BRx), 
                doxy_sim75 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0, -prevGC, -ARx, -BRx),
                doxy_sim90 %>% select(-Inc, -prevB, -prevA, -prevAB, -prev0, -prevGC, -ARx, -BRx))
temp <- lapply(X = df_list, SI.clean)
# names(temp) <- c("doxy_sim_long0", "doxy_sim_long10", "doxy_sim_long25", "doxy_sim_long50", "doxy_sim_long75")
# list2env(temp, envir = .GlobalEnv)

doxy_sim_long0 <- temp[[1]]
doxy_sim_long10 <- temp[[2]]
doxy_sim_long25 <- temp[[3]]
doxy_sim_long50 <- temp[[4]]
doxy_sim_long75 <- temp[[5]]
doxy_sim_long90 <- temp[[6]]
```

```{r}
doxy_sim0 <- doxy_sim0 %>% mutate(DoxyPEP = "0%")
doxy_sim_long0 <- doxy_sim_long0 %>% mutate(DoxyPEP = "0%")

doxy_sim10 <- doxy_sim10 %>% mutate(DoxyPEP = "10%")
doxy_sim_long10 <- doxy_sim_long10 %>% mutate(DoxyPEP = "10%")

doxy_sim25 <- doxy_sim25 %>% mutate(DoxyPEP = "25%")
doxy_sim_long25 <- doxy_sim_long25 %>% mutate(DoxyPEP = "25%")

doxy_sim50 <- doxy_sim50 %>% mutate(DoxyPEP = "50%")
doxy_sim_long50 <- doxy_sim_long50 %>% mutate(DoxyPEP = "50%")

doxy_sim75 <- doxy_sim75 %>% mutate(DoxyPEP = "75%")
doxy_sim_long75 <- doxy_sim_long75 %>% mutate(DoxyPEP = "75%")

doxy_sim90 <- doxy_sim90 %>% mutate(DoxyPEP = "90%")
doxy_sim_long90 <- doxy_sim_long90 %>% mutate(DoxyPEP = "90%")

doxy_sim_all <- rbind(doxy_sim0, doxy_sim10, doxy_sim25, doxy_sim50, doxy_sim75, doxy_sim90)
doxy_sim_long_all <- rbind(doxy_sim_long0, doxy_sim_long10, doxy_sim_long25, doxy_sim_long50, doxy_sim_long75, doxy_sim_long90)
```

```{r}
SI.outputs(doxy_sim0, doxy_sim_long0)
SI.outputs(doxy_sim10, doxy_sim_long10)
SI.outputs(doxy_sim25, doxy_sim_long25)
SI.outputs(doxy_sim50, doxy_sim_long50)
SI.outputs(doxy_sim75, doxy_sim_long75)
SI.outputs(doxy_sim90, doxy_sim_long90)

```

```{r}
doxy_sim_all <- doxy_sim_all %>%
  group_by(DoxyPEP) %>%
  mutate(CumInc = cumsum(Inc),
         CumARx = cumsum(ARx),
         CumBRx = cumsum(BRx),
         IR = Inc/(S1+S2+S3)) %>%
  ungroup()

#output key outcomes by DoxyPEP uptake level
doxy_sim_all %>%
  group_by(DoxyPEP) %>%
  summarise(CumInc5 = CumInc[time == 1825],
            CumInc20 = CumInc[time == 7300],
            Time87 = min(time[prevB >= 0.84])/365,
            ARx5 = CumARx[time == 1825],
            ARx20 = CumARx[time == 7300],
            BRx5 = CumBRx[time == 1825],
            BRx20 = CumBRx[time == 7300]) %>%
  mutate(Rel_CI5 = 1-CumInc5/CumInc5[DoxyPEP == "0%"],
            Rel_CI20 = 1-CumInc20/CumInc20[DoxyPEP == "0%"],
            Rel_A5 = 1-ARx5/ARx5[DoxyPEP == "0%"],
            Rel_A20 = 1-ARx20/ARx20[DoxyPEP == "0%"])
```

```{r}
#Visualize prev and IR of gonorrhea over time, by DoxyPEP uptake level
resB <- doxy_sim_all %>%
  group_by(DoxyPEP) %>%
  summarise(MinT = min(time[prevB >= 0.84]),
            CumInc = CumInc[time == MinT],
            Inc = Inc[time == MinT],
            prevGC = prevGC[time == MinT],
            IR = IR[time==MinT])

#pdf(paste0(filepath, "SF4_DOXYPEP_PrevALL.pdf"), height = 6, width = 8)
prev <- ggplot() +
  geom_line(data = doxy_sim_all, aes(x = time/365, y = prevGC*100, col = factor(DoxyPEP)), size = 1) +
  geom_point(data = resB, aes(x = MinT/365, y = prevGC*100, col = factor(DoxyPEP)), size = 3, shape = 19) +
  theme_classic() + xlab("Years") + ylab("Gonococcal Infection Prevalence (%)") + labs(col = "DoxyPEP Uptake") + theme(text = element_text(size=15), legend.position = c(0.85, 0.25)) +
  scale_color_manual(values = c("#172869", "#6C6C9D","#1BB6AF", "#A6E000", "#FC6882", "#C70E7B"))
prev
#dev.off()
#ggsave(file = paste0(filepath, "SF4_DOXYPEP_PrevALL.svg"), plot = prev, height = 6, width = 8)

# #pdf(paste0(filepath, "DOXYPEP_IncALL.pdf"), height = 6, width = 8)
# inc <- ggplot() +
#   geom_line(data = doxy_sim_all, aes(x = time/365, y = IR*365*100, col = factor(DoxyPEP)), size = 1) +
#   geom_point(data = resB, aes(x = MinT/365, y = IR*365*100, col = factor(DoxyPEP)), size = 3, shape = 19) +
#   theme_classic() + xlab("Years") + ylab("Incidence Rate (Cases/100 PY)") + labs(col = "DoxyPEP Uptake") + theme(text = element_text(size=15), legend.position = c(0.85, 0.25)) +
#   scale_color_manual(values = c("#172869", "#6C6C9D","#1BB6AF", "#A6E000", "#FC6882", "#C70E7B"))
# inc
# #dev.off()
# #ggsave(file = paste0(filepath, "DOXYPEP_IncALL.svg"), plot = inc, height = 6, width = 8)
```

```{r}
baseline <- doxy_sim_all %>%
  filter(DoxyPEP == "0%") %>%
  select(time, 
         IR_compare = IR,
         prev_compare = prevGC,
         CumInc_compare = CumInc)

cumcases <- left_join(doxy_sim_all, baseline) %>%
  mutate(PR = prevGC/prev_compare,
         IRR = IR/IR_compare,
         CasesAverted = CumInc_compare - CumInc)

resB <- cumcases %>%
  group_by(DoxyPEP) %>%
  summarise(MinT = min(time[prevB >= 0.84]),
            PR = PR[time == MinT],
            IRR = IRR[time == MinT],
            CasesAverted = CasesAverted[time == MinT])

cumcases %>%
  group_by(DoxyPEP) %>%
  summarise(min(PR))
```

```{r}
#Visualize PR and IRR relative to baseline (0% DoxyPEP uptake)
#pdf(paste0(filepath, "SF4_DOXYPEP_PR_ALL.pdf"), height = 3, width = 3)
PR <- ggplot() +
  geom_line(data = cumcases, aes(x = time/365, y = PR, col = factor(DoxyPEP)), size = 1) +
  geom_point(data = resB, aes(x = MinT/365, y = PR, col = factor(DoxyPEP)), size = 3, shape = 19) +
  theme_classic() + xlab("Years") + ylab("Prevalence Ratio") + labs(col = "DoxyPEP Uptake") + theme(text = element_text(size=15), legend.position = "none") +
  scale_color_manual(values = c("#172869", "#6C6C9D","#1BB6AF", "#A6E000", "#FC6882", "#C70E7B"))
PR
#dev.off()
#ggsave(file = paste0(filepath, "SF4_DOXYPEP_PR_ALL.svg"), plot = PR, height = 3, width = 3)

# #pdf(paste0(filepath, "DOXYPEP_IRR_ALL.pdf"), height = 3, width = 3)
# IRR <- ggplot() +
#   geom_line(data = cumcases, aes(x = time/365, y = IRR, col = factor(DoxyPEP)), size = 1) +
#   geom_point(data = resB, aes(x = MinT/365, y = IRR, col = factor(DoxyPEP)), size = 3, shape = 19) +
#   theme_classic() + xlab("Years") + ylab("Incidence Rate Ratio") + labs(col = "DoxyPEP Uptake") + theme(text = element_text(size=15), legend.position = "none") +
#   scale_color_manual(values = c("#172869", "#6C6C9D","#1BB6AF", "#A6E000", "#FC6882", "#C70E7B"))
# IRR
# #dev.off()
# #ggsave(file = paste0(filepath, "DOXYPEP_IRR_ALL.svg"), plot = IRR, height = 3, width = 3)
```


```{r}
#Visualize circulating strains (by resistance profile) over time
infectiondat <- doxy_sim_long_all %>%
  filter(Profile != "S" & InfectState != "Exposed") %>%
  group_by(DoxyPEP, time, ResistState) %>%
  summarise(prev = sum(individuals)/10^6) %>%
  mutate(percent = prev/sum(prev)) %>%
  mutate(ResistLabels = ifelse(ResistState == "Neither", "Neither",
                               ifelse(ResistState == "B only", "Doxycycline only",
                                      ifelse(ResistState == "A only", "Ceftriaxone only",
                                             ifelse(ResistState == "A and B", "Ceftriaxone and\nDoxycycline", NA)))))

#pdf(paste0(filepath, "ResistProfileALL.pdf"), width = 7.5, height = 5)
#plot prevalence of gonorrhea over time, by Resistance Profile
ggplot(infectiondat,aes(x=time/365, y=percent*100, fill = factor(ResistLabels, levels = c("Neither", "Doxycycline only", "Ceftriaxone only", "Ceftriaxone and\nDoxycycline")))) +
  geom_area() + scale_fill_manual(values = c("turquoise3", "#E9A17C", "mediumpurple", "deeppink2")) +
  theme_classic() + facet_wrap(~DoxyPEP) +
  xlab("Years") + ylab("% of Gonococcal Infections") + 
  labs(fill = "Resistance Profile", subtitle = "DoxyPEP Uptake Level") +
  theme(legend.position = c(0.84,0.2), plot.subtitle = element_text(hjust = 0.5)) +
  geom_hline(yintercept = 5, col = "white", linetype = "dashed") + geom_hline(yintercept = 84, col = "white", linetype = "dotted")
#dev.off()
```
